'Map of worlds where like creation is enabled and aliases':
- "world:main"
'Like holograms'' text lines':
  'Favorites': "&d&l %favorites% &e&l★"
  'Description': "&6&l%owner%&r&6's Like"
  'Usage': "&6Right click to Like!"
'Tip': "&a【Like】Open like list >> /like list"
'Icon materials on inventory UI':
  'Favorites': "SUNFLOWER"
  'Creation timestamp': "CLOCK"
  'ID': "NAME_TAG"
  'Edit description': "DIAMOND"
  'Unfavorite': "DIAMOND"
  'Go to like teleportation or like invitation confirmation page': "DIAMOND"
  'Teleport to like': "DIAMOND"
  'Cancel like teleportation': "DIAMOND"
  'Invite to like': "DIAMOND"
  'Cancel like invitation': "DIAMOND"
  'Go to like deletion page': "DIAMOND"
  'Delete like': "DIAMOND"
  'Cancel like deletion': "DIAMOND"
  'Like': "SUNFLOWER"
  'Owner''s other likes': "DIAMOND"
  'Sort by creation date in ascending order': "DIAMOND"
  'Sort by creation date in descending order': "DIAMOND"
  'Sort by favorites in ascending order': "DIAMOND"
  'Sort by favorites in descending order': "DIAMOND"
'Number of seconds of like creation cooldown': 10
'Teleportation'
  'Costs': 100.0
  'Message': "&3&l【Like TP】Teleported to Like(%description% by %owner%\n&3)"
'Invitation':
  'Costs': 100.0
  'Radius of scope': 32
  'Message': "&3&l【Like TP】%description% by %owner%\n&3 [%inviter% >> %invitee%] Click to Teleport!"