Worlds:
- "world:メイン"
#ワールド名:エイリアス
TextLines:
  Counter: "&d&l %like_count% &e&l★"
  Lore: "&6&l%player%&r&6's Like"
  Message: "&6Right click to Like!"
TIP: "&a【Like】Open like list >> /like list"
CooldownTime: 10
#秒単位
UpperLimit: 3
#1チャンク内にいくつまでLikeを作成できるか
Items:
  LikeCount: "DIAMOND"
  Timestamp: "DIAMOND"
  Id: "DIAMOND"
  Edit: "DIAMOND"
  Remove1: "DIAMOND"
  Remove2: "DIAMOND"
  Unfavorite: "DIAMOND"
  OtherLike: "DIAMOND"
  ChangeOwner: "DIAMOND"
  PageButton: "DIAMOND"
  LikeIcon: "DIAMOND"
#GUIで表示されるアイテム、参考は→https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
TPCost: 100.0
Invite:
  Cost: 100.0
  Range: 32
  #半径
  Message: "&3&l【Like TP】%Like_text% by %player%\n&3 [Invite user >> %invete_user%] Click to Teleport!"
  #改行は\n