'List of worlds where like creation is enabled and aliases':
- "world:メイン"
'Sequence of like holograms\' text lines':
- "&d&l %favorites% &e&l★"
- "&6&l%maker%&r&6's Like"
- "&6Right click to Like!"
'Tip': "&a【Like】Open like list >> /like list"