Worlds:
- "world:メイン"
#ワールド名:エイリアス
TextLines:
  Counter: "&d&l %like_count% &e&l★"
  Lore: "&6&l%player%&r&6's Like"
  Message: "&6Right click to Like!"
TIP: "&a【Like】Open like list >> /like list"
CooldownTime: 10
#秒単位
UpperLimit: 3
#1チャンク内にいくつまでLikeを作成できるか
Items:
#GUI内での表示
  LikeCount: "SUNFLOWER"
#お気に入り数
  Timestamp: "CLOCK"
#作成日時
  Id: "NAME_TAG"
#管理ID
  Edit: "DIAMOND"
#表示内容の編集
  Remove1: "FIREWORK_STAR"
#削除
  Remove2: "DIAMOND"
#削除(確認画面)
  Unfavorite: "DIAMOND"
#お気に入りの解除
  OtherLike: "DIAMOND"
#作者のその他のLike
  PageButton: "HEART_OF_THE_SEA"
#ページ変更のボタン(自分の作成したLikeリスト・お気に入りに登録したLikeリスト)
  LikeIcon: "SUNFLOWER"
#Likeアイコン(自分の作成したLikeリスト・お気に入りに登録したLikeリスト)
#GUIで表示されるアイテム、参考は→https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
TPCost: 100.0
Invite:
  Cost: 100.0
  Range: 32
  #半径
  Message: "&3&l【Like TP】%Like_text% by %player%\n&3 [Invite user >> %invete_user%] Click to Teleport!"
  #改行は\n