name: Like
main: amata1219.like.Main
version: 1.1.0
depend: [HolographicDisplays, Vault, PCGF_PluginLib]
author: amata1219(Twitter@amata1219)

default-permission-message: &denied You don't have <permission>
commands:
  like:
    permission: like.like
    permission-message: *denied
  likec:
    permission: like.like
    permission-message: *denied
  likel:
    permission: like.like
    permission-message: *denied
  likes:
    permission: like.like
    permission-message: *denied
  liketoken:
    permission: like.like
    permission-message: *denied
  likeb:
    permission: like.like
    permission-message: *denied
  likeop:
    permission: like.likeop
    permission-message: *denied